# Generated by Django 3.0.7 on 2020-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_placeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['position'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения места'},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
