# Generated by Django 3.0.7 on 2020-06-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20200615_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='position',
            field=models.IntegerField(verbose_name='Позиция'),
        ),
    ]
