# Generated by Django 3.0.7 on 2020-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_auto_20200615_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['sort'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения места'},
        ),
        migrations.RemoveField(
            model_name='placeimage',
            name='position',
        ),
        migrations.AddField(
            model_name='placeimage',
            name='sort',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
