# Generated by Django 3.0.7 on 2020-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20200615_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['sorting'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения места'},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='sorting',
            field=models.PositiveIntegerField(default=0, verbose_name='Позиция'),
        ),
    ]
