# Generated by Django 3.0.7 on 2020-06-15 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20200615_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['id'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['my_order'], 'verbose_name': 'Изображение места', 'verbose_name_plural': 'Изображения места'},
        ),
        migrations.RenameField(
            model_name='placeimage',
            old_name='sorting',
            new_name='my_order',
        ),
    ]
